### ISSUE TITLE
Cloud Parallel samples crash

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.StarterKit#83]
1. Open ```2-cloud-parallel.fsx```
2. Execute code up to line 16.
3. Execute lines 52 - 54.
4. Execute lines 52 - 54.

```
System.IO.FileLoadException: Cannot resolve dependency to assembly 'MBrace.Core, Version=1.0.13.0, Culture=neutral, PublicKeyToken=null' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Nessos.Vagabond.AssemblyParser.tryRemapReferencedType(AssemblyCompilerState state, Type t) in C:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\AssemblyParser.fs:line 96
   at Nessos.Vagabond.Utils.memoize@171.Invoke(a x) in C:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Utils.fs:line 175
   at Nessos.Vagabond.AssemblyParser.parseConfiguration@150.Nessos-Vagabond-AssemblyParser-IAssemblyParserConfig-RemapReference(Type type, Type& outType) in C:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\AssemblyParser.fs:line 175
   at Nessos.Vagabond.AssemblyParser.AssemblyParser.MapReference(Type t, TypeReference type)
   at Nessos.Vagabond.AssemblyParser.AssemblyParser.CreateReference(MethodBase method, MethodReference context)
   at Nessos.Vagabond.AssemblyParser.AssemblyParser.MapInstructions(MethodBase method, MethodDefinition method_definition)
   at Nessos.Vagabond.AssemblyParser.AssemblyParser.MapMethodBody(MethodBase method, MethodDefinition method_definition)
   at Nessos.Vagabond.AssemblyParser.AssemblyParser.MapType(Type type, TypeDefinition declaringType)
   at Nessos.Vagabond.AssemblyParser.AssemblyParser.Map()
   at Nessos.Vagabond.AssemblyParser.parseDynamicAssemblySlice(AssemblyCompilerState state, Assembly assembly) in C:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\AssemblyParser.fs:line 182
   at Nessos.Vagabond.SliceCompiler.compileDynamicAssemblySlice(AssemblyCompilerState state, Assembly dynamicAssembly) in C:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\AssemblyCompiler.fs:line 71
   at Nessos.Vagabond.SliceCompiler.compileAssembly(AssemblyCompilerState state, Assembly assembly) in C:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\AssemblyCompiler.fs:line 124
   at Nessos.Vagabond.SliceCompiler.compileAssemblies@134-1.Invoke(Assembly assembly) in C:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\AssemblyCompiler.fs:line 137
   at Nessos.Vagabond.Utils.MailboxProcessor`1.PostAndReply[Msg,R](FSharpMailboxProcessor`1 m, FSharpFunc`2 msgB) in C:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Utils.fs:line 297
   at Nessos.Vagabond.VagabondManager.ComputeObjectDependencies(Object graph, FSharpOption`1 permitCompilation, FSharpOption`1 includeNativeDependencies) in C:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Vagabond.fs:line 114
   at MBrace.Runtime.Components.StoreAssemblyManager.ComputeDependencies[T](T graph) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime\Components\StoreAssemblyManager.fs:line 294
   at <StartupCode$MBrace-Runtime>.$MBraceClient.CreateProcessAsync@65.Invoke(Unit unitVar) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime\Runtime\MBraceClient.fs:line 66
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
   at MBrace.Core.Internals.AsyncExtensions.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Utils\AsyncExtensions.fs:line 99
   at <StartupCode$FSI_0006>.$FSI_0006.main@() in C:\Users\Isaac\Source\Repos\MBrace.StarterKit\HandsOnTutorial\2-cloud-parallel.fsx:line 52
Stopped due to error
```

**Comment by eiriktsarpalis** [comment]
Hmmm, I can't reproduce this. Are you using VS2015?
